config/routes.rb
Rails.application.routes.draw do
  get 'contributors', to: 'contributors#index'
  get '/contributors/:id', to: 'contributors#show', as: 'contributor'
  devise_for :users
  resources :topics
  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_and_belongs_to_many :users

  validates :title, :body, presence: true
  validates :title, :body, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :topics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  def index
    @contributors = User.all
  end

  def show
    @contributor = User.find(params[:id])
    @topics = @contributor.topics
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @topics = Topic.all
  end

  def show
    @users = @topic.users
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      @topic.users << current_user unless contains? @topic
      redirect_to @topic, notice: 'Topic was successfully created.'
    else
      render :new
    end
  end

  def update
    if @topic.update(topic_params)
      @topic.users << current_user unless contains? @topic
      redirect_to @topic, notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_url, notice: 'Topic was successfully destroyed.'
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :body)
  end

  def contains?(topic)
    topic.users.include? current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contributors/index.html.erb
<h1>Contributors</h1>
<ul>
  <% @contributors.each do |c| %>
    <li>
      <%= link_to contributor_path(c) do %>
        <%= c.email %>
      <% end %>
    </li>
  <% end %>
</ul>
<hr/>
<%= link_to "Back", topics_path %>

app/views/contributors/show.html.erb
<h1><%= @contributor.email %>'s contributions</h1>

<ul>
  <% if @topics.any? %>
    <% @topics.each do |topic| %>
      <li>
        <%= link_to topic_path(topic) do %>
          <%= topic.title %>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <li>This user hasn't contributed yet.</li>
  <% end %>
</ul>

<hr/>

<div>
  <%= link_to "Contributors", contributors_path %> |
  <%= link_to "Topics", topics_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FootballFancy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
  <%= link_to("Log Out", destroy_user_session_path,
      method: :delete) %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path  %>
    <%= link_to "Sign In", new_user_session_path(@user) %>
  <% end %>

  <p id="notice"><%= notice %></p>

  <%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div>
  <%= link_to "New Topic", new_topic_path %> |
  <%= link_to "Contributors", contributors_path %>
</div>

<br/>

<hr/>

<% @topics.each do |topic| %>
  <h3><%= topic.title %></h3>
  <p><%= topic.body %></p>
  <div>
    <%= link_to 'Show', topic %> |
    <%= link_to 'Edit', edit_topic_path(topic) %> |
    <%= link_to 'Destroy', topic, method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </div>
  <hr/>
<% end %>
<br>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p>
  <strong>Title:</strong><br/>
  <%= @topic.title %>
</p>


<p>
  <strong>Body:</strong><br/>
  <%= @topic.body %>
</p>

<p><strong>Contributors:</strong></p>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to contributor_path(user) do %>
          <%= user.email %>
      <% end %>
    </li>
  <% end %>
</ul>

<hr/>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %> |
<%= link_to('Destroy', topic_path, method: :delete,
    data: { confirm: 'Are you sure?' }) %>